### ISSUE TITLE
ggpredict and gamlss 

### ISSUE THREAD

**Issue by fbognoun** [strengejacke/ggeffects#101]
**Question and context**
I am using ggpredict to compute the predicted  values for the response in gamlss with Zero inflated beta negative binomial distribution denoted by ZIBNB (µ, σ, ν, τ). So far I succed to extract the predicted values of µ, but I am stuck in extracting the predicted values of σ, ν, τ. How can I implement ggpredict to extract the predicted values of σ, ν, τ in gamlss models?

**Comment by strengejacke** [comment]
``` r
library(ggeffects)
library(gamlss)
data(abdom)
m1 <- gamlss(
  y ~ pb(x),
  sigma.formula =  ~ pb(x),
  family = BCT,
  data = abdom,
  method = mixed(1, 20)
)

ggpredict(m1, "x")
#> new prediction 
#> New way of prediction in pb()  (starting from GAMLSS version 5.0-3)
#> 
#> # Predicted values of y
#> # x = x
#> 
#>   x predicted std.error conf.low conf.high
#>  10    31.141     0.812   29.551    32.732
#>  15    94.584     0.591   93.426    95.742
#>  20   152.327     0.455  151.434   153.219
#>  25   205.393     0.483  204.447   206.339
#>  30   258.861     0.653  257.582   260.140
#>  35   308.761     0.887  307.023   310.500
#>  40   352.326     1.147  350.079   354.574
#>  45   392.463     1.418  389.684   395.241

ggpredict(m1, "x", what = "sigma")
#> new prediction 
#> New way of prediction in pb()  (starting from GAMLSS version 5.0-3)
#> 
#> # Predicted values of y
#> # x = x
#> 
#>   x predicted std.error conf.low conf.high
#>  10    -2.405     0.812   -3.996    -0.815
#>  15    -2.643     0.591   -3.801    -1.484
#>  20    -2.882     0.455   -3.774    -1.989
#>  25    -3.042     0.483   -3.988    -2.096
#>  30    -3.050     0.653   -4.330    -1.771
#>  35    -2.984     0.887   -4.722    -1.245
#>  40    -2.929     1.147   -5.176    -0.681
#>  45    -2.896     1.418   -5.675    -0.117
```

<sup>Created on 2019-10-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
You need to update [_insight_](https://github.com/easystats/insight) and _ggeffects_ from **GitHub** if you want to already have the changes available.

**Comment by fbognoun** [comment]
Many thank for your quick response. I am trying to update ggeffecs from GitHub without success. 

ERROR: package installation failed
Error: Failed to install 'ggeffects' from GitHub:
  System command error, exit status: 1, stdout + stderr (last 10 lines):
E> ** R
E> ** data
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Erreur : object 'get_varcov' is not exported by 'namespace:insight'
E> Exécution arrêtée
E> ERROR: lazy loading failed for package 'ggeffects'
E> * removing 'C:/Users/fbognoun/AppData/Local/Temp/Rtmpsp1qdY/Rinst3838145532b7/ggeffects'
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by strengejacke** [comment]
Have you also installed _insight_ from GitHub? (see my reply)

**Comment by fbognoun** [comment]
Many thank for your help! It succeded to test it with the example from the abdomen data.
But when I tryed to applied it to my model it did not work. In my model, the set of explanatory variables of mu.formula differs from those of sigma.formula,nu.formula and tau.formula. 
My model looks like:
Mod0<-gamlss(Y ~ A + B + C, 
         sigma.formula = ~D + E + F + D:E,  
       nu.formula = ~E + F, 
       tau.formula = ~A + E + F + A:F, 
       family = ZIBNB, data = data1)

When I run 
ggpredict(Mod0, terms = "A",what="tau")

Error in eval(predvars, data, env) : object 'E' not found

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by fbognoun** [comment]
Here is an example. 
library(gamlss)
> data(usair)
> Mod<-gamlss(y ~ x1+x2+x3, 
+                  sigma.formula = ~x4+x5+x6+x4:x5,  
+                  nu.formula = ~x2+x5, 
+                  tau.formula = ~x1+x4+x5+x6+x1:x4, 
+                  family = ZIBNB, data = usair)
GAMLSS-RS iteration 1: Global Deviance = 318.4196 
GAMLSS-RS iteration 2: Global Deviance = 301.5592 
GAMLSS-RS iteration 3: Global Deviance = 300.3385 
GAMLSS-RS iteration 4: Global Deviance = 300.2979 
GAMLSS-RS iteration 5: Global Deviance = 300.291 
GAMLSS-RS iteration 6: Global Deviance = 300.29 
GAMLSS-RS iteration 7: Global Deviance = 300.29 
> library(ggeffects)
> ggpredict(Mod, terms = "x1")
Error: Confidence intervals could not be computed.
* Reason: "the Hessian matrix is singular probably the model is overparametrised"
* Source: vcov.gamlss(x)

# Predicted values of y
# x = x1

  x predicted
 42    68.870
 46    54.124
 50    42.535
 54    33.428
 60    23.289
 64    18.302
 68    14.384
 76     8.883

Adjusted for:
* x2 = 463.10
* x3 = 608.61

> ggpredict(Mod, terms = "x4",what="sigma")
Error in eval(predvars, data, env) : object 'x5' not found
> ggpredict(Mod, terms = "x2",what="nu")
Error in eval(predvars, data, env) : object 'x5' not found
> ggpredict(Mod, terms = "x1",what="tau")
Error in eval(predvars, data, env) : object 'x4' not found

**Comment by strengejacke** [comment]
Ok, should be fixed in https://github.com/easystats/insight/commit/b806966b3ec3937d531f784c79d26adfc3515966.

**Comment by fbognoun** [comment]
May I understand that the isue will be fixed if I update insight package?

**Comment by strengejacke** [comment]
yes, from GitHub

**Comment by fbognoun** [comment]
I uninstalled and reinstalled the insigth package from GitHub, and also uninstalled and reinstalled the ggeffect package from Github, but the problem is still not solve. I got the same errors I sent you yesterday.  

Here are the codes of the example
install_github("easystats/insight")
library(insight)
install_github("strengejacke/ggeffects")
library(ggeffects)
library(gamlss)
data(usair)
Mod<-gamlss(y ~ x1+x2+x3, 
                 sigma.formula = ~x4+x5+x6+x4:x5,  
                 nu.formula = ~x2+x5, 
                 tau.formula = ~x1+x4+x5+x6+x1:x4, 
                 family = ZIBNB, data = usair)

ggpredict(Mod, terms = "x1")
ggpredict(Mod, terms = "x4",what="sigma")
ggpredict(Mod, terms = "x2",what="nu")
ggpredict(Mod, terms = "x1",what="tau")

**Comment by fbognoun** [comment]
Hi again,
Many thanks for the support. ggpredict is working fine with sigma, nu and tau. However the predicted value of tau is out of range. The predicted value of tau is supposed to vary between 0 and 1, but I am geting value higher than 1. Is it possible to fix that?

**Comment by strengejacke** [comment]
I must see if this is a ggpredict issue. I'll look at it next week, on vacation currently.

**Comment by strengejacke** [comment]
Can't reproduce your issue. This is what I get:

``` r
library(ggeffects)
library(gamlss)
data(usair)
Mod<-gamlss(y ~ x1+x2+x3,
            sigma.formula = ~x4+x5+x6+x4:x5,
            nu.formula = ~x2+x5,
            tau.formula = ~x1+x4+x5+x6+x1:x4,
            family = ZIBNB, data = usair)

pr <- ggpredict(Mod, terms = "x1",what="tau")
pr
#> 
#> # Predicted values of y
#> # x = x1
#> 
#>   x predicted
#>  42         0
#>  46         0
#>  50         0
#>  54         0
#>  60         0
#>  64         0
#>  68         0
#>  76         0
#> 
#> Adjusted for:
#> * x2 = 463.10
#> * x3 = 608.61
#> * x4 =   9.44
#> * x5 =  36.77
#> * x6 = 113.90

as.data.frame(pr)
#>     x    predicted group
#> 1  42 2.220446e-16     1
#> 2  44 2.220446e-16     1
#> 3  46 2.220446e-16     1
#> 4  48 2.220446e-16     1
#> 5  50 2.220446e-16     1
#> 6  52 2.220446e-16     1
#> 7  54 2.220446e-16     1
#> 8  56 2.220446e-16     1
#> 9  58 2.220446e-16     1
#> 10 60 2.220446e-16     1
#> 11 62 2.220446e-16     1
#> 12 64 2.220446e-16     1
#> 13 66 2.220446e-16     1
#> 14 68 2.220446e-16     1
#> 15 70 2.220446e-16     1
#> 16 72 2.220446e-16     1
#> 17 74 2.220446e-16     1
#> 18 76 2.220446e-16     1

linv <- insight::link_inverse(Mod)
linv(predict(Mod, newdata = new_data(Mod, "x1"), what = "tau"))
#>  [1] 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16
#>  [6] 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16
#> [11] 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16
#> [16] 2.220446e-16 2.220446e-16 2.220446e-16

predict(Mod, newdata = new_data(Mod, "x1"), what = "tau", type = "response")
#>  [1] 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16
#>  [6] 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16
#> [11] 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16
#> [16] 2.220446e-16 2.220446e-16 2.220446e-16
```

<sup>Created on 2019-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by fbognoun** [comment]
Hi Daniel,
Hope had pleasant vacation.
I am providing a more appropriate example for the issus of tau in GMALSS.
library(gamlss)
> zinb <- read.csv("https://stats.idre.ucla.edu/stat/data/fish.csv")
> str(zinb)
'data.frame':	250 obs. of  8 variables:
 $ nofish  : int  1 0 0 0 0 0 0 0 1 0 ...
 $ livebait: int  0 1 1 1 1 1 1 1 0 1 ...
 $ camper  : int  0 1 0 1 0 1 0 0 1 1 ...
 $ persons : int  1 1 1 2 1 4 3 4 3 1 ...
 $ child   : int  0 0 0 1 0 2 1 3 2 0 ...
 $ xb      : num  -0.896 -0.558 -0.402 -0.956 0.437 ...
 $ zg      : num  3.05 1.746 0.28 -0.602 0.528 ...
 $ count   : int  0 0 0 0 1 0 0 0 0 1 ...
> Mod<-gamlss(count~child,
+                     sigma.formula =~1,
+                     nu.formula =~1,
+                     tau.formula=~child,
+                     family=ZIBNB,
+             control=gamlss.control(n.cyc = 100,iter = 30,
+                                    c.crit = 0.99999),data=zinb)
GAMLSS-RS iteration 31: Global Deviance = 890.2904 
GAMLSS-RS iteration 32: Global Deviance = 885.5713 
GAMLSS-RS iteration 33: Global Deviance = 881.6756 
GAMLSS-RS iteration 34: Global Deviance = 878.7929 
GAMLSS-RS iteration 35: Global Deviance = 876.669 
GAMLSS-RS iteration 36: Global Deviance = 875.6586 
GAMLSS-RS iteration 37: Global Deviance = 875.0093 
> pt<-ggpredict(Mod, terms = "child",what="tau")
> as.data.frame(pt)
  x   predicted  std.error   conf.low   conf.high group
1 0  0.06555676 0.02852055 0.06199273   0.0693257     1
2 1  0.46282112 0.46173006 0.18723534   1.1440329     1
3 2  3.26744913 0.95198063 0.50568661  21.1123324     1
4 3 23.06771105 1.44223119 1.36576219 389.6134326     1
> zinb$TauPred<-lpred(Mod, what="tau",type ="response", newdata=zinb)# to get tau predicted value
> range(zinb$TauPred)
[1] 0.06152348 0.95845056

You can see that the ggpredict has two value higher than 1 while the range of the predicted tau spans between 0.06 and 0.96.

**Comment by strengejacke** [comment]
ok, should be fixed now, but requires the very latest GitHub-version of [insight](https://github.com/easystats/insight).

**Comment by fbognoun** [comment]
Hi Daniel,
Thank you so much! It is workingfine now.
Best regards,
Fidèle

**Comment by elliechesterton** [comment]
Hi @strengejacke sorry to bump this old thread, but I'm also experiencing the same issue above. I'm trying to run ggeffects on a gamlss model to calculate/plot the marginal effects, but I'm getting an error. 

I'm using gamlss 5.4–3, ggeffects 1.1.2, and insight 0.180

Example of my model: 

> model <- gamlss(y ~ x1 + random(factor(x2)),
                           family=BEINF,
                           data = data)

> (model_pred <- ggpredict(model, terms="x1"))

Error in `[.data.frame`(data, match(names(newdata), names(data))) : 
  undefined columns selected

Any help would be really appreciated! Thank you

**Comment by strengejacke** [comment]
> Hi @strengejacke sorry to bump this old thread, but I'm also experiencing the same issue above. I'm trying to run ggeffects on a gamlss model to calculate/plot the marginal effects, but I'm getting an error.
> 
> I'm using gamlss 5.4–3, ggeffects 1.1.2, and insight 0.180
> 
> Example of my model:
> 
> > model <- gamlss(y ~ x1 + random(factor(x2)),
> > family=BEINF,
> > data = data)
> 
> > (model_pred <- ggpredict(model, terms="x1"))
> 
> Error in `[.data.frame`(data, match(names(newdata), names(data))) : undefined columns selected
> 
> Any help would be really appreciated! Thank you

Do you have a reproducible example?
